
const Constants = {
  REGISTRATION_ERROR: 'REGISTRATION_ERROR',

  CURRENT_USER: 'CURRENT_USER',
  USER_SIGNED_OUT: 'USER_SIGNED_OUT',
  SESSION_ERROR: 'SESSION_ERROR',

  GET_AVAILABLE_SKILLS: 'GET_AVAILABLE_SKILLS',
  ACKNOWLEDGE_UPDATE_STATUS: 'ACKNOWLEDGE_UPDATE_STATUS',

  ADD_RECOMMENDATION: 'ADD_RECOMMENDATION',
  RECOMMENDATION_ADD_ERROR: 'RECOMMENDATION_ADD_ERROR'
};

export default Constants;
